/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.laboon;

import org.junit.Test;
import static org.junit.Assert.*;

public class SampleAppTest {
    @Test public void testSampleAppHasAGreeting() {
        SampleApp classUnderTest = new SampleApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
